module.exports = {
    USER_ALREADY_REGISTERED: 'USER_ALREADY_REGISTERED',
    USER_DOSE_NOT_EXIST: 'USER_DOSE_NOT_EXIST',
    WE_DO_NOT_HAVE_REPORT_FOR_THIS_TIME: 'WE_DO_NOT_HAVE_REPORT_FOR_THIS_TIME',
    ACCESS_DENIED : 'ACCESS_DENIED',
    INVALID_LONG_URL : 'INVALID_LONG_URL',
    ERROR_IN_CREATING_SHORT_URL: 'ERROR_IN_CREATING_SHORT_URL',
    CANNOT_INSERT_NEW_VIEW: 'CANNOT_INSERT_NEW_VIEW',
}