module.exports = {
    USER_ALREADY_REGISTERED: 'USER_ALREADY_REGISTERED',
    USER_DOSE_NOT_EXIST: 'USER_DOSE_NOT_EXIST',
    WE_DO_NOT_HAVE_REPORT_FOR_THIS_TIME: 'WE_DO_NOT_HAVE_REPORT_FOR_THIS_TIME',
    ACCESS_DENIED : 'ACCESS_DENIED',
}